# Generated by Django 6.1 on 2026-08-14 22:41

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="avatars/",
                validators=[core.validators.validate_avatar_size],
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(300),
                ],
                verbose_name="О себе",
            ),
        ),
    ]
