# Generated by Django 6.1 on 2026-08-16 15:56

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_avatar_alter_customuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="avatars/",
                validators=[core.validators.validate_avatar_size],
                verbose_name="Аватар",
            ),
        ),
    ]
