# Generated by Django 6.1 on 2026-08-16 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(300),
                ],
                verbose_name="О себе",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
    ]
