# Generated by Django 6.1 on 2026-08-14 22:41

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(300),
                ],
                verbose_name="Текст поста",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="post_images/",
                validators=[core.validators.validate_image_size],
                verbose_name="Изображение",
            ),
        ),
    ]
