# Generated by Django 6.1 on 2026-08-16 15:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_content_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="post_images/",
                validators=[core.validators.validate_image_size],
                verbose_name="Изображение",
            ),
        ),
    ]
